# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
# must be created in the azure UI under Pipelines > Library and specify accessKey, secretKey, region, and bucket
- group: 's3-public-bucket-upload'
- name: sdk
  value: macosx
- name: xcodeVersionNum
  value: 11

pool:
  vmImage: 'macos-latest'

stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: Xcode@5
          displayName: Build MorphicCore
          inputs:
            actions: 'build'
            sdk: $(sdk)
            scheme: 'MorphicCore'
            configuration: 'Release'
            xcWorkspacePath: '**/MorphicLite.xcworkspace'
            xcodeVersion: $(xcodeVersionNum)
        - task: Xcode@5
          displayName: Build MorphicService
          inputs:
            actions: 'build'
            sdk: $(sdk)
            scheme: 'MorphicService'
            configuration: 'Release'
            xcWorkspacePath: '**/MorphicLite.xcworkspace'
            xcodeVersion: $(xcodeVersionNum)
        - task: Xcode@5
          displayName: Build MorphicConfigurator
          inputs:
            actions: 'build'
            sdk: $(sdk)
            scheme: 'MorphicConfigurator'
            configuration: 'Release'
            xcWorkspacePath: '**/MorphicLite.xcworkspace'
            xcodeVersion: $(xcodeVersionNum)
        - task: Xcode@5
          displayName: Build MorphicSettings
          inputs:
            actions: 'build'
            sdk: $(sdk)
            scheme: 'MorphicSettings'
            configuration: 'Release'
            xcWorkspacePath: '**/MorphicLite.xcworkspace'
            xcodeVersion: $(xcodeVersionNum)
        - task: Xcode@5
          displayName: Build Morphic
          inputs:
            actions: 'build'
            sdk: $(sdk)
            scheme: 'Morphic'
            configuration: 'Release'
            xcWorkspacePath: '**/MorphicLite.xcworkspace'
            xcodeVersion: $(xcodeVersionNum)
        - task: Bash@3
          displayName: publish to s3
          env:
            AWS_ACCESS_KEY_ID: $(accessKey)
            AWS_SECRET_ACCESS_KEY: $(secretKey)
            BUCKET: $(bucket)
            AWS_DEFAULT_REGION: $(region)
            BRANCH: $(Build.SourceBranch)
            BRANCH_NAME: $(Build.SourceBranchName)
          inputs:
            targetType: 'inline'
            script: |
              set -e

              CLIENT_NAME=""
              if [[ "${BRANCH_NAME}" == "master" ]]; then
                CLIENT_NAME="Morphic.app"
              fi
              if [[ "${BRANCH_NAME}" == "develop" ]]; then
                CLIENT_NAME="Morphic-latest.app"
              fi
              if [[ "${BRANCH}" == *"tags"* ]]; then
                CLIENT_NAME="Morphic-${BRANCH_NAME}.app"
              fi

              if [[ "$CLIENT_NAME" == "" ]]; then
                #echo "no client name found. will not publish to s3"
                #exit 0
                CLIENT_NAME="Morphic-test.app"
              fi

              set -x

              find ${AGENT_HOMEDIRECTORY}

              pwd
              export
              ls -al ${AGENT_BUILDDIRECTORY}
              ls -alr *

              # seems to be installed already
              # ref: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
              aws s3 cp Build/Products/Release/MorphicConfigurator.app s3://${BUCKET}/osx/$CLIENT_NAME