# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

strategy:
  matrix:
    mac-10-14:
      imageName: 'macOS-10.14'
      sdk: foo
    mac-10-15:
      imageName: 'macos-10.15'
      sdk: bar
  maxParallel: 1

pool:
  vmImage: $(imageName)

steps:
- task: Xcode@5
  displayName: Build MorphicCore
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicCore'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: Build MorphicService
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicService'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: Build MorphicConfigurator
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicConfigurator'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: Build MorphicSettings
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicSettings'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: Build MorphicMenuBar
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicMenuBar'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
