# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
  sdk: macosx
  xcodeVersionNum: 11

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  displayName: Build MorphicCore
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicCore'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicService
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicService'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicConfigurator
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicConfigurator'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicSettings
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicSettings'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicMenuBar
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicMenuBar'
    configuration: 'Release'
    xcWorkspacePath: '**/MorphicLite.xcworkspace'
    xcodeVersion: $(xcodeVersionNum)
